version: '2'

volumes:
  kafka-ssl-secrets:
  kafka-ssl-config:

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.12-2.4.0
    labels:
      - io.github.ssledz.service=kafka-ssl
    ports:
      - "9092"
      - "9093"
    environment:
#      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:SSL
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
#      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://_{HOSTNAME_COMMAND}:9093
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://:9093
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9093
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
#      KAFKA_LISTENERS: 'SSL://:9092'
#      KAFKA_ADVERTISED_LISTENERS: 'SSL://_{HOSTNAME_COMMAND}:9092'
      KAFKA_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/kafka.broker.keystore.jks
      KAFKA_SSL_KEYSTORE_PASSWORD: kafkatest
      KAFKA_SSL_KEY_PASSWORD: kafkatest
      KAFKA_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/kafka.broker.truststore.jks
      KAFKA_SSL_TRUSTSTORE_PASSWORD: kafkatest
      KAFKA_SSL_CLIENT_AUTH: 'none'
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ''
      KAFKA_LISTENER_NAME_INTERNAL_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ''
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - kafka-ssl-secrets:/etc/kafka/secrets:ro
    depends_on:
      - kafka-ssl
  kafka-ssl:
    image: ssledz/volume/kafka-ssl
    volumes:
      - kafka-ssl-secrets:/etc/kafka/secrets
      - kafka-ssl-config:/etc/kafka/cfg
